sudo: required

language: python 

services:
      - docker

before_install:


before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce
    - docker pull ubuntu:xenial 
	- docker run hello-world
      # - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
      # - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
    # - docker run -d -p 127.0.0.1:80:4567 jtest/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
      # - docker ps -a
      # - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# script:
#     - bundle exec rake test
